--- # AGS2 Menu structure
- About:
  - rank: 1
  - note: 'MEGA AGS 2022.11.22'
  - Nothing to see here:
    - rank: 1
    - note: Intentionally left blank.

- Hall of Fame:
  - rank: 2
  - note: Games inducted into the Megaboys Hall of Fame.\nSorted by genre.
  - image: { ops: { op: pi, path: "top/hall_of_fame.png" }, size: [320, 128 ], scale: [1, 1] }
  - Action:
    - CannonFodder

- Current:
  - image: [{ op: "tx", txt: "ASS" }, { op: "tx", txt: "P*SS", size: 100, color: "#f0f" }]
  - ProximaHopscotch
  - SuperDeliveryBoyHS
  - game--anotherworldfr--anotherworldfr
  - game--anotherworld--anotherworld
  - game--anotherworldit--anotherworldit
  - game--anotherworldlostlevel--anotherworldlostlevel
  - demo--anotherworldintro--anotherworld
  - demo-notwhdl--crystal-anotherworld
  - game--legendofthelost--legendofthelost

- Ordering Tests:
  - Ranked (2):
    - rank: 2
    - ordering: "ranked"
    - note: From /v/'s Recommended Games Wiki
    - Agony
    - ShadowOfTheBeast
  - Ordered (3):
    - rank: 3
    - ordering: "ordered"
    - note: 45 Games That Defined the AMIGA 500, according to It's a P/XEL thing.\n\n(Chronologically ordered.)
    - IK+
    - BatmanTheMovie
    - StuntCarRacer: { rank: 0 }
    - ItCameFromTheDesert
    - Populous
  - Release (1):
    - rank: 1
    - ordering: "release"
    - note: By release date
    - EyeOfTheBeholder2
    - Lemmings
    - Speedball2
    - Turrican2
    - Worms

- Test:
  - note: Test for builder options
  - Andromeda-Rule30: { scale: 6, v_offset: 48 }
  - Bacteria
  - BaygonAGA: Melon!
  - BrunosMusicBox3: { v_offset: 4, image: { op: "tx", txt: "BRUNO", size: 90 } }
  - Coma: { note: COMA! }
  - Nested:
    - How2SkinACat
    - Delphine-Collection: { unavailable: True }
    - HumanTarget
    - Interference
