#!/bin/bash

date_str=$1

if [ -z "$date_str" ]; then
  echo "No archive suffix";
else
  arc_name="AmigaVision-$date_str.7z"
  7z a -xr'!.*' -mx=7 -myx=5 $arc_name _Computer/ _Console/ config/ Filters/ games/ Presets/ Shadow_Masks/ Extras.7z Extras.txt History.txt ReadMe.txt;
fi
