#!/bin/bash

date_str=$1

if [ -z "$date_str" ]; then
  echo "No archive suffix";
else
  arc_name="MegaAGS-$date_str.7z"
  7z a -xr'!.*' -mx=7 -myx=5 $arc_name MegaAGS-ReadMe.txt MegaAGS-Extras.txt MegaAGS-History.txt MegaAGS-Extras.7z config/ games/ _Computer/ Filters/ Presets/ Shadow_Masks/;
fi
