- Disk Mags:
  - rank: 7
  - note: Full Disk Magazine category for the A500 Mini build.
  - mags--42issue1--42issue1
  - mags--42issue1aga--42issue1aga
  - mags--42issue2--42issue2
  - demo-notwhdl--ds!up-a1
  - mags--almighty--almighty
  - mags--compass1--compass1
  - mags--crackerjournal01--crackerjournal01
  - mags--crackerjournal02--crackerjournal02
  - mags--crackerjournal03--crackerjournal03
  - mags--crackerjournal04--crackerjournal04
  - mags--crackerjournal05--crackerjournal05
  - mags--crackerjournal06--crackerjournal06
  - mags--crackerjournal07&08--crackerjournal07&08
  - mags--crackerjournal09--crackerjournal09
  - mags--crackerjournal10--crackerjournal10
  - mags--crackerjournal11--crackerjournal11
  - mags--crackerjournal12--crackerjournal12
  - mags--crackerjournal13--crackerjournal13
  - mags--crackerjournal14--crackerjournal14
  - mags--crackerjournal15--crackerjournal15
  - mags--crackerjournal16--crackerjournal16
  - mags--crackerjournal17--crackerjournal17
  - mags--crackerjournal18--crackerjournal18
  - mags--crackerjournal19--crackerjournal19
  - mags--crackerjournal20--crackerjournal20
  - mags--crackerjournal21--crackerjournal21
  - mags--crackerjournal22--crackerjournal22
  - mags--disc1--disc1
  - mags--disc2--disc2
  - mags--disc3--disc3
  - mags--disc4--disc4
  - mags--disc5--disc5
  - mags--disc6--disc6
  - mags--disc7--disc7
  - mags--disc8--disc8
  - mags--eurochart01--eurochart01
  - mags--eurochart02--eurochart02
  - mags--eurochart03--eurochart03
  - mags--eurochart04--eurochart04
  - mags--eurochart05--eurochart05
  - mags--eurochart06--eurochart06
  - mags--eurochart07--eurochart07
  - mags--eurochart08--eurochart08
  - mags--eurochart09--eurochart09
  - mags--eurochart10--eurochart10
  - mags--eurochart11--eurochart11
  - mags--eurochart12--eurochart12
  - mags--eurochart13--eurochart13
  - mags--eurochart14--eurochart14
  - mags--eurochart15--eurochart15
  - mags--eurochart16--eurochart16
  - mags--eurochart17--eurochart17
  - mags--eurochart18--eurochart18
  - mags--eurochart19--eurochart19
  - mags--eurochart20--eurochart20
  - mags--eurochart21--eurochart21
  - mags--eurochart22--eurochart22
  - mags--eurochart23--eurochart23
  - mags--eurochart24--eurochart24
  - mags-notwhdl--eurochart25
  - mags-notwhdl--eurochart26
  - mags-notwhdl--eurochart27
  - mags-notwhdl--eurochart28
  - mags-notwhdl--eurochart29
  - mags-notwhdl--eurochart30
  - mags-notwhdl--eurochart31
  - mags-notwhdl--eurochart32
  - mags-notwhdl--eurochart33
  - mags-notwhdl--eurochart34
  - mags-notwhdl--eurochart35
  - mags-notwhdl--eurochart36
  - mags-notwhdl--eurochart37
  - mags-notwhdl--eurochart38
  - mags-notwhdl--eurochart39
  - mags-notwhdl--eurochart40
  - mags-notwhdl--eurochart41
  - mags-notwhdl--eurochart42
  - mags-notwhdl--eurochart43
  - mags-notwhdl--eurochart44
  - mags-notwhdl--eurochart45
  - mags-notwhdl--eurochart46
  - mags-notwhdl--eurochart47
  - mags-notwhdl--eurochart48
  - mags--fourthdimension1--fourthdimension1
  - mags--fourthdimension2--fourthdimension2
  - mags--fourthdimension3--fourthdimension3
  - mags--grapevine01--grapevine01
  - mags--grapevine02--grapevine02
  - mags--grapevine03--grapevine03
  - mags--grapevine04--grapevine04
  - mags--grapevine05--grapevine05
  - mags--grapevine06--grapevine06
  - mags--grapevine07--grapevine07
  - mags--grapevine08--grapevine08
  - mags--grapevine09--grapevine09
  - mags--grapevine10--grapevine10
  - mags--grapevine11--grapevine11
  - mags--grapevine12--grapevine12
  - mags--grapevine13--grapevine13
  - mags--grapevine14--grapevine14
  - mags--grapevine15--grapevine15
  - mags--grapevine16--grapevine16
  - mags--grapevine17--grapevine17
  - mags--grapevine18--grapevine18
  - mags--grapevine19--grapevine19
  - mags--grapevine20--grapevine20
  - mags--grapevine21--grapevine21
  - mags--ice01--ice01
  - mags--ice02--ice02
  - mags--ice3--ice3
  - mags--ice4--ice4
  - mags--ice5--ice5
  - mags--ice6--ice6
  - mags--ice7--ice7
  - mags--ice8--ice8
  - mags--mcdisk1--mcdisk1
  - mags--mcdisk2--mcdisk2
  - mags--mcdisk3--mcdisk3
  - mags-notwhdl--oepirristi01
  - mags-notwhdl--oepirristi02
  - mags-notwhdl--oepirristi03
  - mags-notwhdl--oepirristi04
  - mags-notwhdl--oepirristi05
  - mags-notwhdl--oepirristi06
  - mags-notwhdl--oepirristi07
  - mags-notwhdl--oepirristi07ic
  - mags-notwhdl--oepirristi08
  - mags-notwhdl--oepirristi09
  - mags-notwhdl--oepirristi10
  - mags--penis1--penis1
  - mags--penis2--penis2
  - mags--penis3--penis3
  - mags--rom1--rom1
  - mags--rom2--rom2
  - mags-notwhdl--rom03
  - mags-notwhdl--rom04
  - mags-notwhdl--rom05
  - mags-notwhdl--rom06
  - mags-notwhdl--rom07
  - mags-notwhdl--rom08
  - mags-notwhdl--rom09
  - mags-notwhdl--raw01
  - mags-notwhdl--raw02
  - mags-notwhdl--raw03
  - mags-notwhdl--raw05
  - mags--scenetalk1--scenetalk1
  - mags--scenetalk2--scenetalk2
  - mags--scenetalk3--scenetalk3
  - mags--scenetalk4--scenetalk4
  - mags--scenetalk5--scenetalk5
  - mags--scenetalk6--scenetalk6
  - mags--scenetalk7--scenetalk7
  - mags--scenetalk8--scenetalk8
  - mags--stolendata01--stolendata01
  - mags-notwhdl--stolendata02
  - mags-notwhdl--stolendata03
  - mags-notwhdl--stolendata04
  - mags-notwhdl--stolendata05
  - mags--stolendata07--stolendata07
  - mags--stolendata08--stolendata08
  - mags--stolendata09--stolendata09
  - mags--stolendata10--stolendata10
  - mags--scene1--scene1
  - mags--scene2abel--scene2abel
  - mags--scene3decay--scene3decay
  - mags--scene4prophecy--scene4prophecy
  - mags--upstream01--upstream01
  - mags-notwhdl--upstream06
  - mags-notwhdl--upstream07
  - mags-notwhdl--upstream08
  - mags-notwhdl--upstream09
  - mags-notwhdl--upstream10
  - mags--visualintensity1--visualintensity1
  - mags--worldcharts01--worldcharts01
  - mags--worldcharts02--worldcharts02
  - mags--worldcharts03--worldcharts03
  - mags--worldcharts04--worldcharts04
  - mags--worldcharts05--worldcharts05
  - mags--worldcharts07--worldcharts07
  - mags--worldcharts09--worldcharts09
  - mags--worldcharts10--worldcharts10
  - mags--worldcharts11--worldcharts11
  - mags--worldcharts12--worldcharts12
  - mags--worldcharts13--worldcharts13
  - mags-notwhdl--worldcharts15
  - mags--zine01--zine01
  - mags--zine02--zine02
  - mags--zine03--zine03
  - mags--zine04--zine04
  - mags--zine05--zine05
  - mags--zine06--zine06
  - mags--zine07--zine07
  - mags--zine08--zine08
  - mags--zine09--zine09
  - mags--zine10--zine10
  - mags--zine11--zine11
