- 060 Demos:
  - rank: 6
  - note: Demo productions that require AGA/060 hardware.
  - demo-notwhdl--focusdesign-1992-060
  - demo-notwhdl--focusdesign-bekoolfool-060
  - demo-notwhdl--capsule-brutalism-060
  - demo-notwhdl--flex-deadahead-060
  - demo-notwhdl--spaceballs-goonroyale
  - demo-notwhdl--ephidrena-hexel-060
  - demo-notwhdl--ephidrena-knarkzilla-060
  - demo-notwhdl--ghostown-lasttraintodanzig-060
  - demo-notwhdl--logicoma-entropychamber-060
  - demo-notwhdl--noice-lastgoatstanding-060
  - demo-notwhdl--theblacklotus-oceanmachine-060
  - demo-notwhdl--theblacklotus-silkcut-060
  - demo-notwhdl--theblacklotus-starstruck-060
  - demo-notwhdl--unique-subside-060
