- Music Disks:
  - rank: 6
  - note: Full Music Disk category for the A500 Mini build.
  - demo--100mostrememberedc64tunes--100mostrememberedc64tunes
  - demo--2unlimitednolimit--2unlimitednolimit
  - demo--24hourefix--24hourefix
  - demo--3dnetanalyzer--3dnetanalyzer
  - demo--8bitjungle--8bitjungle
  - demo--afewtunes--afewtunes
  - demo--absenceoflight--absenceoflight
  - demo--absoluteswedish--absoluteswedish
  - demo--musiquedisk--musiquedisk
  - demo--acidinthehouse--acidinthehouse
  - demo--acousticsilence--acousticsilence
  - demo--musicdiskactionforce--musicdiskactionforce
  - demo--musicdisk1adammccrory--musicdisk1adammccrory
  - demo--musicdisk1alcatraz--musicdisk1alcatraz
  - demo--alfredthemusicdisk--alfredthemusicdisk
  - demo--allweneedismusic5--allweneedismusic5
  - demo--amazingtunes--amazingtunes
  - demo--amazingtunes2--amazingtunes2
  - demo--amplifier1--amplifier1
  - demo--amplifier2--amplifier2
  - demo--artofnoise3--artofnoise3
  - demo--artofnoise4--artofnoise4
  - demo--atmosphericalmelodies--atmosphericalmelodies
  - demo--audiomega--audiomega
  - demo--audienceislistening--audienceislistening
  - demo--audiodreams--audiodreams
  - demo--audiorhythm2--audiorhythm2
  - demo--audioviolation--audioviolation
  - demo--audiox--audiox
  - demo--auralillusions--auralillusions
  - demo--autumnnights--autumnnights
  - demo--bigdemo--bigdemo
  - demo--back2base--back2base
  - demo--bacteria--bacteria
  - demo--bangingraves--bangingraves
  - demo--bangingraves2--bangingraves2
  - demo--bardinabox--bardinabox
  - demo--musicdisk1bass--musicdisk1bass
  - demo--bassomatic--bassomatic
  - demo--bassocontinuo--bassocontinuo
  - demo--beastsonix--beastsonix
  - demo--beatbox--beatbox
  - demo--beatvise--beatvise
  - demo--bestofpearl--bestofpearl
  - demo--bestofrafvol1--bestofrafvol1
  - demo--birthday--birthday
  - demo--blackenergy--blackenergy
  - demo--blueshouse--blueshouse
  - demo--bluessymphoniesaga--bluessymphoniesaga
  - demo--bombthebasstuneshow2--bombthebasstuneshow2
  - demo--bookofsongs--bookofsongs
  - demo--musicland--musicland
  - demo--musicland2--musicland2
  - demo--bestofgrubi--bestofgrubi
  - demo--breedcd1--breedcd1
  - demo--brunosmusicbox3--brunosmusicbox3
  - demo--brunosmusicbox2--brunosmusicbox2
  - demo--muzzax1--muzzax1
  - demo--muzzax2--muzzax2
  - demo--muzzax3--muzzax3
  - demo--muzzax4--muzzax4
  - demo--muzzax5--muzzax5
  - demo--muzzax6--muzzax6
  - demo--muzzax7--muzzax7
  - demo--callitwotyawant--callitwotyawant
  - demo--celebration--celebration
  - demo--cerebraldelights--cerebraldelights
  - demo-notwhdl--cheesylistening
  - demo--cherokee--cherokee
  - demo--chipattack--chipattack
  - demo--chipmusic--chipmusic
  - demo--chipmusicfestival--chipmusicfestival
  - demo--chords--chords
  - demo--chromagic--chromagic
  - demo--clappingworld--clappingworld
  - demo--colorcrime--colorcrime
  - demo--compactmusicdisk1--compactmusicdisk1
  - demo--complete--complete
  - demo--conceptcriminosical--conceptcriminosical
  - demo--tunedisk1--tunedisk1
  - demo--musicboxcopyride--musicboxcopyride
  - demo--crazysounds2--crazysounds2
  - demo--creamycranium1--creamycranium1
  - demo--musicdiskcryptic--musicdiskcryptic
  - demo--musicparty1990--musicparty1990
  - demo--crystalsymphonies--crystalsymphonies
  - demo--crystalsymphonies2--crystalsymphonies2
  - demo--cutcreations--cutcreations
  - demo--cybersounds--cybersounds
  - demo--musicdisk3dmob--musicdisk3dmob
  - demo--musicdisk1dmob--musicdisk1dmob
  - demo--musicdisk4dmob--musicdisk4dmob
  - demo--dancediversevol1--dancediversevol1
  - demo--dancetrance--dancetrance
  - demo--dancetrance2--dancetrance2
  - demo--dancewar--dancewar
  - demo--musicdisk2darkness--musicdisk2darkness
  - demo--deadlyjammin2--deadlyjammin2
  - demo--decibeloverload--decibeloverload
  - demo--musicdemodeform--musicdemodeform
  - demo--delicatesounds--delicatesounds
  - demo--deliriumkronical--deliriumkronical
  - demo--musicdiskdexion--musicdiskdexion
  - demo--difficulttocureaga--difficulttocureaga
  - demo--digitalconcert--digitalconcert
  - demo--digitalconcert2--digitalconcert2
  - demo--digitalconcert3--digitalconcert3
  - demo--digitalconcert4--digitalconcert4
  - demo--digitalconcert5--digitalconcert5
  - demo--digitalconcert6--digitalconcert6
  - demo--digitalnoises--digitalnoises
  - demo--digitalsounds1--digitalsounds1
  - demo--discofever--discofever
  - demo--musicdiscvol1disknet--musicdiscvol1disknet
  - demo--divineinspiration--divineinspiration
  - demo--dizzytunes--dizzytunes
  - demo--dizzytunes2--dizzytunes2
  - demo--dothebartman--dothebartman
  - demo--dogscogsaga--dogscogsaga
  - demo--donmartinmusicdisk--donmartinmusicdisk
  - demo--dontpanic--dontpanic
  - demo--musicdiskdreamscape--musicdiskdreamscape
  - demo--drums&pipes--drums&pipes
  - demo--drums&reverbs--drums&reverbs
  - demo--dynamo--dynamo
  - demo--eargasmtunes--eargasmtunes
  - demo--earwig--earwig
  - demo--electricsound3--electricsound3
  - demo--elektrica--elektrica
  - demo--musicdisk2elite--musicdisk2elite
  - demo--musics3--musics3
  - demo--epilepsia--epilepsia
  - demo--epilepsia2--epilepsia2
  - demo--musicdiskescape--musicdiskescape
  - demo--essentialbeats3--essentialbeats3
  - demo--essentialclassics--essentialclassics
  - demo--estprobalmastic--estprobalmastic
  - demo--exage--exage
  - demo--musiccollectionexocet--musiccollectionexocet
  - demo--musicboxexodus--musicboxexodus
  - demo--expressions--expressions
  - demo--extemporized--extemporized
  - demo--faceanotherday--faceanotherday
  - demo--musabox--musabox
  - demo--musabox2--musabox2
  - demo--fantasticdream--fantasticdream
  - demo--musicdisk1fantasyforce--musicdisk1fantasyforce
  - demo--musicdisk2--musicdisk2
  - demo--finlandia--finlandia
  - demo--foolsgold--foolsgold
  - demo--fourseasons--fourseasons
  - demo--fractaltunes--fractaltunes
  - demo--futuresynthetix--futuresynthetix
  - demo--musicbox3--musicbox3
  - demo--gatetohell--gatetohell
  - demo--musicmegademo2--musicmegademo2
  - demo--gladiatormusic--gladiatormusic
  - demo--grapevinemegamix--grapevinemegamix
  - demo--greatesthits--greatesthits
  - demo--groovyjives3--groovyjives3
  - demo--hailtheengineer--hailtheengineer
  - demo--hismastersnoise--hismastersnoise
  - demo--hitcollection1--hitcollection1
  - demo--hotmusic1--hotmusic1
  - demo--hotmusic3--hotmusic3
  - demo--hotmusic4--hotmusic4
  - demo--housemusic--housemusic
  - demo--hymn633--hymn633
  - demo--hymnsfromthebible3--hymnsfromthebible3
  - demo--musicdisk1iks--musicdisk1iks
  - demo--musicdisk2iks--musicdisk2iks
  - demo--imaginations--imaginations
  - demo--imperialtunes--imperialtunes
  - demo--imperialtunes2--imperialtunes2
  - demo--infinitedreamslunatics--infinitedreamslunatics
  - demo--musicdiskinzzest--musicdiskinzzest
  - demo--musicdiskipecelite--musicdiskipecelite
  - demo--musicmadness--musicmadness
  - demo--musicmadness2--musicmadness2
  - demo--itsjustthebeginning--itsjustthebeginning
  - demo--jesterday--jesterday
  - demo--jiggleit--jiggleit
  - demo--jochenhippelsounddemo--jochenhippelsounddemo
  - demo--jukebox--jukebox
  - demo--junglemania--junglemania
  - demo--just4yourears--just4yourears
  - demo--kakburk--kakburk
  - demo--kaostheory--kaostheory
  - demo--musiccollectionkatharsis--musiccollectionkatharsis
  - demo--multimegamix--multimegamix
  - demo--multimegamix2--multimegamix2
  - demo--multimegamix3--multimegamix3
  - demo--kraftwerkmegamix--kraftwerkmegamix
  - demo--kuglepoelen--kuglepoelen
  - demo--legaliseit--legaliseit
  - demo--legalizeit2--legalizeit2
  - demo--legoland--legoland
  - demo--lethalfrequency--lethalfrequency
  - demo--musicdiskaspect&orix--musicdiskaspect&orix
  - demo--teatime--teatime
  - demo--loonytunes--loonytunes
  - demo--lostsymphony--lostsymphony
  - demo--losttrack--losttrack
  - demo--lovesongs--lovesongs
  - demo--maestrojamsvol1--maestrojamsvol1
  - demo--magnumicetro--magnumicetro
  - demo--musicdisk1mahoney&kaktus--musicdisk1mahoney&kaktus
  - demo--manicraves2--manicraves2
  - demo--meanbreakmachine2--meanbreakmachine2
  - demo--megatraxvol1--megatraxvol1
  - demo--tuneshow2--tuneshow2
  - demo--megablast--megablast
  - demo-notwhdl--uprough-megamix
  - demo--memorialsongs--memorialsongs
  - demo--merrymelodies--merrymelodies
  - demo--microconcept--microconcept
  - demo--miamivicetheme--miamivicetheme
  - demo--mindfield--mindfield
  - demo--minisoundbox1--minisoundbox1
  - demo--minisoundbox2--minisoundbox2
  - demo--minisoundbox3--minisoundbox3
  - demo--minordefects--minordefects
  - demo--miraclesounds1--miraclesounds1
  - demo--mirror--mirror
  - demo--mixolydian--mixolydian
  - demo--monolith--monolith
  - demo--musiccompacting2--musiccompacting2
  - demo--musicforfools--musicforfools
  - demo--musicalmassacre--musicalmassacre
  - demo--musicalrabbit--musicalrabbit
  - demo--musication--musication
  - demo--muzakcompacting1--muzakcompacting1
  - demo--sounddisk1--sounddisk1
  - demo--sounddisk2--sounddisk2
  - demo--newage--newage
  - demo--nightshadesharmony--nightshadesharmony
  - demo--nobrainnopainparadise--nobrainnopainparadise
  - demo--nonstopmusic--nonstopmusic
  - demo--numeric--numeric
  - demo--numeric2--numeric2
  - demo--numeric3--numeric3
  - demo--odetoramon--odetoramon
  - demo--odetoramon2--odetoramon2
  - demo--odeon--odeon
  - demo--odysounds2--odysounds2
  - demo--oldtunes--oldtunes
  - demo--onedayonmars--onedayonmars
  - demo--opticaldreams--opticaldreams
  - demo--orgasm--orgasm
  - demo--overload--overload
  - demo--overload2--overload2
  - demo--sploosh15pond--sploosh15pond
  - demo--packvanpee1--packvanpee1
  - demo--packvanpee3--packvanpee3
  - demo--panicvoicesofenergy--panicvoicesofenergy
  - demo--paralyticnoises--paralyticnoises
  - demo--pastelvanilla--pastelvanilla
  - demo--musicdream1--musicdream1
  - demo--musicdream2--musicdream2
  - demo--2unlimited--2unlimited
  - demo--sounddiskpossessed--sounddiskpossessed
  - demo--powertrax--powertrax
  - demo-notwhdl--nectarine-preampii
  - demo-notwhdl--abyss-preschoolno1
  - demo-notwhdl--abyss-preschoolno2
  - demo--projectbeat--projectbeat
  - demo--projecttechno--projecttechno
  - demo--musicdisk1prologic--musicdisk1prologic
  - demo--propagandazerodefects--propagandazerodefects
  - demo--psychic--psychic
  - demo--quickmusique--quickmusique
  - demo--megamix1--megamix1
  - demo--megamix2--megamix2
  - demo--megamix3--megamix3
  - demo--rainheartproject--rainheartproject
  - demo--musicdisk6ramjam--musicdisk6ramjam
  - demo--musiccompilation--musiccompilation
  - demo--rapiscrap--rapiscrap
  - demo--raverance--raverance
  - demo--revolutions--revolutions
  - demo--rhythmdevice--rhythmdevice
  - demo--rhythmnation--rhythmnation
  - demo--rockbox1--rockbox1
  - demo--rockbox2--rockbox2
  - demo--rolling--rolling
  - demo--royalmusic--royalmusic
  - demo--royalmusic2--royalmusic2
  - demo--scrmusax2--scrmusax2
  - demo--smau92musicdisk--smau92musicdisk
  - demo--sanesounds--sanesounds
  - demo--melodies--melodies
  - demo--muzaksdisk1--muzaksdisk1
  - demo--seductionaga--seductionaga
  - demo--shakeyourself--shakeyourself
  - demo--sigh--sigh
  - demo--musicrip2--musicrip2
  - demo--songsrackaga--songsrackaga
  - demo--songsofinfinity--songsofinfinity
  - demo--sonicattack--sonicattack
  - demo--sonicalfantasia--sonicalfantasia
  - demo--soundandvision--soundandvision
  - demo--soundandvision2--soundandvision2
  - demo--soundataxvol1--soundataxvol1
  - demo--soundataxvol2--soundataxvol2
  - demo--soundataxvol3--soundataxvol3
  - demo--soundbarrier--soundbarrier
  - demo--sounddelight--sounddelight
  - demo--sounddemosyndicate--sounddemosyndicate
  - demo--soundengine--soundengine
  - demo--soundengine2--soundengine2
  - demo--sounderection--sounderection
  - demo--soundhighlights1--soundhighlights1
  - demo--soundmania2pussy--soundmania2pussy
  - demo--soundquest1--soundquest1
  - demo--soundquest2--soundquest2
  - demo--soundrevolution6--soundrevolution6
  - demo--soundtrip--soundtrip
  - demo--soundofmusic7--soundofmusic7
  - demo--soundofsilents--soundofsilents
  - demo--soundbox2--soundbox2
  - demo--soundsofgnome--soundsofgnome
  - demo--soundtrackerinjury--soundtrackerinjury
  - demo--soundtrackerinjury2--soundtrackerinjury2
  - demo--soundtrackerinjury3--soundtrackerinjury3
  - demo--soundtrackerinjury4--soundtrackerinjury4
  - demo--spacedoutvol1--spacedoutvol1
  - demo--spacedoutvol2--spacedoutvol2
  - demo--sphericaldreams--sphericaldreams
  - demo--sploosh--sploosh
  - demo--musicrip3--musicrip3
  - demo--springmelodies--springmelodies
  - demo--starlight--starlight
  - demo--stereosounds--stereosounds
  - demo--strangemusic1--strangemusic1
  - demo--strangemusic2--strangemusic2
  - demo--strangemusic3--strangemusic3
  - demo--subconscious--subconscious
  - demo--sweetmusic--sweetmusic
  - demo--syntheticpower--syntheticpower
  - demo--syntheticvibes--syntheticvibes
  - demo--tacticaltransmissions--tacticaltransmissions
  - demo--talktime1--talktime1
  - demo--musicdisktardex--musicdisktardex
  - demo--technotrance--technotrance
  - demo--technotrance3--technotrance3
  - demo--technowarrior--technowarrior
  - demo--technomania--technomania
  - demo--technomania2--technomania2
  - demo--tekknobert--tekknobert
  - demo--teratunes--teratunes
  - demo--teratunes2--teratunes2
  - demo--thalionsounddemo--thalionsounddemo
  - demo--musicdisk181sttrack--musicdisk181sttrack
  - demo--musicdisk281sttrack--musicdisk281sttrack
  - demo--musicdiskthrust--musicdiskthrust
  - demo--titantrax--titantrax
  - demo--topkaraoke1--topkaraoke1
  - demo--topkaraoke2aga--topkaraoke2aga
  - demo--topkaraoke3aga--topkaraoke3aga
  - demo--totalkaos--totalkaos
  - demo--toxicwaste--toxicwaste
  - demo--eroticon6--eroticon6
  - demo--tuneshow3--tuneshow3
  - demo--turmoil--turmoil
  - demo--turricanmusicdisk--turricanmusicdisk
  - demo--turricanmusicshow--turricanmusicshow
  - demo--tympanicmembrane--tympanicmembrane
  - demo--ufonix--ufonix
  - demo--unleashed--unleashed
  - demo--musicdisk1vega--musicdisk1vega
  - demo--musicdisk2vega--musicdisk2vega
  - demo--musicdisk3vega--musicdisk3vega
  - demo--musicdisk4vega--musicdisk4vega
  - demo--viktoria--viktoria
  - demo--virtualharmony--virtualharmony
  - demo--musicdiskarmada&it--musicdiskarmada&it
  - demo--walkmanmusic--walkmanmusic
  - demo--wavesound--wavesound
  - demo--wickedhouse--wickedhouse
  - demo--worldofnoise1--worldofnoise1
  - demo--worldswave--worldswave
  - demo--worldswave2--worldswave2
  - demo--worldswave3--worldswave3
  - demo--worldswave4--worldswave4
  - demo--musiccollection4zarch--musiccollection4zarch
  - demo--sounddiskzenith--sounddiskzenith
  - demo--zilliondreams--zilliondreams
  - demo--musicalsecrets--musicalsecrets
