- Crack Intros:
  - rank: 5
  - note: A small curated set of classic crack intros for the A500 Mini build.
  - demo-notwhdl--paranoimia-anothercrack
  - demo-notwhdl--paranoimia-anotherfirst
  - demo-notwhdl--ministry-cytron
  - demo--ministry projectxse--ministry
  - demo--shinobiintro--shinobiintro
  - demo--sunsetglow--sunsetglow
  - demo-notwhdl--paranoimia-turicon
  - demo-notwhdl--paranoimia-xout
  - demo-notwhdl--redsector-plutos
  - demo--unita fa18interceptor--unit-a
  - demo--scoopexcolorado--scoopex
  - demo--rollingthunderintro--rollingthunderintro
  - demo--supermanintro--supermanintro
  - demo--testdriveintro--testdrive
  - demo--blackmonks testdrive2--blackmonks
