- Exclude:
  - hidden: true
  - BeneathAStlSkyCD32
  - BiingAGADe
  - BumpNBurnCD32
  - CapitalPunishmentAGA
  - CastleOfDrBrainNTSCMT32
  - ConquestsOfTheLongbowMT32
  - CoverGirlStripPoker
  - Emmanuelle
  - EmmanuelleDe
  - EmmanuelleEs
  - EmmanuelleFr
  - EvilsDoomAGA
  - HollywoodPoker
  - HollywoodPokerPro
  - KingsQuest5MT32
  - KingsQuest5RmDeMT32
  - KingsQuest5RmEsMT32
  - KingsQuest5RmItMT32
  - KingsQuest5RmMT32
  - KingsQuestEnhanced--MT32
  - LeisureSuitLarry
  - LeisureSuitLarry2
  - LeisureSuitLarry3
  - LeisureSuitLarry3De
  - LeisureSuitLarry5
  - LeisureSuitLarry5De
  - LeisureSuitLarryEnhanced
  - LeisureSuitLarry5MT32
  - LeisureSuitLarryEnhndMT32
  - LiberationCD32
  - MixedUpMotherGooseMT32
  - PoliceQuest3NTSCMT32
  - PlayhouseStripPoker
  - PokerNights
  - PokerNights&DataDisks
  - QuestForGlory2MT32
  - RiseOfTheRobotsAGA
  - demo--acme1991slideshow--acme1991slideshow
  - demo--art&go--art&go
  - demo--assembly92slideshow--assembly92slideshow
  - demo--blacknwhite--blacknwhite
  - demo--bohemian--bohemian
  - demo--borisvallejoslide--borisvallejoslide
  - demo--diggypiggys--diggypiggys
  - demo--ecesslideshow--ecesslideshow
  - demo--fantasticart--fantasticart
  - demo--fantasticpixvol1--fantasticpixvol1
  - demo--forgotten--forgotten
  - demo--gathering93slideshow--gathering93slideshow
  - demo--gathering91slideshow--gathering91slideshow
  - demo--hollywoodpokerslide--hollywoodpokerslide
  - demo--honeycomb--honeycomb
  - demo--juggler--juggler
  - demo-notwhdl--daltonmarkferrari
  - demo--masterpieces--masterpieces
  - demo--metal&lace--metal&lace
  - demo--mindoftraces--mindoftraces
  - demo--morbidvisions--morbidvisions
  - demo--morbidvisions2--morbidvisions2
  - demo--morbidvisions3--morbidvisions3
  - demo--museum--museum
  - demo--party2slideshow--party2slideshow
  - demo--prism--prism
  - demo--psygnosismusicpicturedisc--psygnosismusicpicturedisc
  - demo--raytraceddreams--raytraceddreams
  - demo--sevenseas--sevenseas
  - demo--sexvens--sexvens
  - demo--shedtears--shedtears
  - demo--stag1--stag1
  - demo--stag2--stag2
  - demo--stag3--stag3
  - demo--stag4--stag4
  - demo--stag5--stag5
  - demo--stag6--stag6
  - demo--stagextra--stagextra
  - demo--stagseries--stagseries
  - demo--sunaga--sunaga
  - demo--swelteringforest--swelteringforest
  - demo--visionoftheart--visionoftheart
  - demo--wildaga--wildaga
  - demo--worldofmangaaga--worldofmangaaga
  - SpaceQuest4NTSCMT32
  - SpaceQuestEnhanced--MT32
  - StripPoker
  - StripPoker2
  - StripPoker2+
  - StripPoker2+&DataDisk1
  - StripPoker3
  - StripPoker3&DataDisks
  - SuperSkidmarks+CD
  - SuprStrtFtr2TrboAGA
